DATA SEGMENT
    STRING DB 0AH DUP(?)  
    MSG DB "Enter the string: $"  
    NEWLINE DB 0AH,0DH,"Lowercase: $"
    LEN DB ?
DATA ENDS

DISPLAY MACRO ARG
    MOV AH,09H
    LEA DX,ARG
    INT 21H
ENDM

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX    
   
    DISPLAY MSG 
    MOV AH,0AH
    LEA DX,STRING
    MOV STRING,0FFH
    INT 21H   
    LEA SI,STRING
    MOV CL,[SI+1]
    MOV LEN,CL
    MOV CH,00
RE: MOV AL,[SI+2]  
    CMP AL,41H
    JC SKIP
    CMP AL,5BH
    JNC SKIP
    ADD AL,20H
    MOV [SI+2],AL
SKIP:INC SI
    LOOP RE
    DISPLAY NEWLINE
    LEA SI,STRING
    MOV CL,LEN
OUTPUT:MOV AH,02H
    MOV DX,[SI+2]
    INC SI
    INT 21H
    LOOP OUTPUT
    
EOC:MOV AH,01H
    INT 21H  
    MOV AX,4CH
    INT 21H     
   
CODE ENDS
END START